{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hypelab",
    "module": "hypelab-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "hypelab-sdk-1.0.0.aar",
          "url": "hypelab-sdk-1.0.0.aar",
          "size": 206007,
          "sha512": "a6c488d952bee9923414a3f9910db0ae78f191b273453b204c6c9a1d04bdc9c088057e70860f52622fa425c5381c4ce73d6019374190b32380c26946a7da40e5",
          "sha256": "a2b671e269bbb7f1773ae192985344344bec5415fb5f63995105e8e5f34897ee",
          "sha1": "6ee2b0d5c1589bd67474147dbab75260486b4bfd",
          "md5": "c0fa7d70a54437d9d3c192ef75479349"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.1.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "hypelab-sdk-1.0.0.aar",
          "url": "hypelab-sdk-1.0.0.aar",
          "size": 206007,
          "sha512": "a6c488d952bee9923414a3f9910db0ae78f191b273453b204c6c9a1d04bdc9c088057e70860f52622fa425c5381c4ce73d6019374190b32380c26946a7da40e5",
          "sha256": "a2b671e269bbb7f1773ae192985344344bec5415fb5f63995105e8e5f34897ee",
          "sha1": "6ee2b0d5c1589bd67474147dbab75260486b4bfd",
          "md5": "c0fa7d70a54437d9d3c192ef75479349"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "hypelab-sdk-1.0.0-sources.jar",
          "url": "hypelab-sdk-1.0.0-sources.jar",
          "size": 154022,
          "sha512": "d4697e27476ae5c1a3e439f7684816e681f77dc2f8e0597ecf7fdf9bc8e5e85f99686ccdff7bbab2c141f7e7eda01474352a95cc4d6ce43bd07694e531771495",
          "sha256": "66c23d1dd114442a93d939f027bc7ab74047bce965997fba300d4cf638295c56",
          "sha1": "4248820a8af21e02c82ce0941fa15ce0160900f3",
          "md5": "b014926669cc49b3df459cacb296bd35"
        }
      ]
    }
  ]
}
